name: support_asu
description: Support asu front project
version: 0.0.1

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ^4.0.0
  angular_forms: ^1.0.0
  http: ^0.11.0
  angular_router: ^1.0.2
  dartson: ">=0.2.0 <0.3.0"

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- dartson
- angular:
    entry_points: web/main.dart
- dart_to_js_script_rewriter
