// <auto-generated />
namespace SupportAsu.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AlterPurchaseAddNote : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterPurchaseAddNote));
        
        string IMigrationMetadata.Id
        {
            get { return "201706170940463_AlterPurchaseAddNote"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
